# Introducción

# Preparación de los datos

Comenzaremos importando nuestras librerías y cargando nuestros datasets

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from scipy import stats as st

In [2]:
calls = pd.read_csv("datasets/telecom_dataset_new.csv")
clients = pd.read_csv("datasets/telecom_clients.csv")

# Exploración de los datos

## calls

In [39]:
calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53902 entries, 0 to 53901
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              53902 non-null  int64
 1   date                 53902 non-null  object
 2   direction            53902 non-null  object
 3   internal             53785 non-null  object
 4   operator_id          45730 non-null  float64
 5   is_missed_call       53902 non-null  bool
 6   calls_count          53902 non-null  int64
 7   call_duration        53902 non-null  int64
 8   total_call_duration  53902 non-null  int64
dtypes: bool(1), float64(1), int64(4), object(3)
memory usage: 3.3+ MB

In [40]:
calls.head()

,user_id,date,direction,internal,operator_id,is_missed_call,calls_count,call_duration,total_call_duration
0,166377,2019-08-04 00:00:00+03:00,in,False,NaN,True,2,0,4
1,166377,2019-08-05 00:00:00+03:00,out,True,880022.0,True,3,0,5
2,166377,2019-08-05 00:00:00+03:00,out,True,880020.0,True,1,0,1
3,166377,2019-08-05 00:00:00+03:00,out,True,880020.0,False,1,10,18
4,166377,2019-08-05 00:00:00+03:00,out,False,880022.0,True,3,0,25

In [41]:
calls.tail()

,user_id,date,direction,internal,operator_id,is_missed_call,calls_count,call_duration,total_call_duration
53897,168606,2019-11-10 00:00:00+03:00,out,True,957922.0,True,1,0,38
53898,168606,2019-11-11 00:00:00+03:00,out,True,957922.0,False,2,479,501
53899,168606,2019-11-15 00:00:00+03:00,out,True,957922.0,False,4,3130,3190
53900,168606,2019-11-15 00:00:00+03:00,out,True,957922.0,False,4,3130,3190
53901,168606,2019-11-19 00:00:00+03:00,in,False,NaN,True,2,0,64

In [60]:
calls_in = calls[calls["direction"] == "in"]

calls_in.isna().sum()

user_id                   0
date                      0
direction                 0
internal                115
operator_id            7972
is_missed_call            0
calls_count               0
call_duration             0
total_call_duration       0
dtype: int64

In [59]:
calls_out = calls[calls["direction"] == "out"]

calls_out.isna().sum()

user_id                  0
date                     0
direction                0
internal                 2
operator_id            200
is_missed_call           0
calls_count              0
call_duration            0
total_call_duration      0
dtype: int64

In [42]:
calls.duplicated().sum()

np.int64(4900)

In [ ]:
calls_dup = calls[calls.duplicated() == True]

# clients

In [43]:
clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      732 non-null    int64
 1   tariff_plan  732 non-null    object
 2   date_start   732 non-null    object
dtypes: int64(1), object(2)
memory usage: 17.3+ KB

In [44]:
clients.head()

   user_id tariff_plan  date_start
0   166713           A  2019-08-15
1   166901           A  2019-08-23
2   168527           A  2019-10-29
3   167097           A  2019-09-01
4   168193           A  2019-10-16

In [45]:
clients.tail()

     user_id tariff_plan  date_start
727   166554           B  2019-08-08
728   166911           B  2019-08-23
729   167012           B  2019-08-28
730   166867           B  2019-08-22
731   166565           B  2019-08-08

In [46]:
clients.duplicated().sum()

np.int64(0)